$(function(){
  $("#show-menu").click(function(){
    $("#menu").fadeIn();
  });
  $("#close").click(function(){
    $("#menu").fadeOut();
  });
  /*OPUSモーダル1*/
  $("#opus-show1").click(function(){
    $("#opus1").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus1").fadeOut("fast");
  });
  /*OPUSモーダル2*/
  $("#opus-show2").click(function(){
    $("#opus2").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus2").fadeOut("fast");
  });
  /*OPUSモーダル3*/
  $("#opus-show3").click(function(){
    $("#opus3").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus3").fadeOut("fast");
  });
  /*OPUSモーダル4*/
  $("#opus-show4").click(function(){
    $("#opus4").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus4").fadeOut("fast");
  });
  /*OPUSモーダル5*/
  $("#opus-show5").click(function(){
    $("#opus5").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus5").fadeOut("fast");
  });
  /*OPUSモーダル6*/
  $("#opus-show6").click(function(){
    $("#opus6").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus6").fadeOut("fast");
  });
  /*OPUSモーダル7*/
  $("#opus-show7").click(function(){
    $("#opus7").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus7").fadeOut("fast");
  });
  /*OPUSモーダル8*/
  $("#opus-show8").click(function(){
    $("#opus8").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus8").fadeOut("fast");
  });
  /*OPUSモーダル9*/
  $("#opus-show9").click(function(){
    $("#opus9").fadeIn("fast");
  });
  $(".close").click(function(){
    $("#opus9").fadeOut("fast");
  });
});
